# Generated by Django 5.2.6 on 2025-12-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
