# Generated by Django 5.2.6 on 2025-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
